language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: noteapp-v1
  api_key:
    secure: IFe6Uwy4ZSji9O1oF26kXYolmF97d84iw0xTmDjqKODGLd8t7E82HnhvNhlDKWws8E+/mxkxxXctm7tj9ry7JmcmWWVg3cEQEc91V/jbA6CIRW4RwXj03NaehE2VxheVElfh8x4qsCQbFUUf0VR4IOw5FpCQfq+XXHbzKn/rurJEptJQ0jDe9pegk/Yay9vvY4JIgnFUi6qgxA2X0plZNLYf0UkNzYQ9+OcS9moLAg1yTsUbBAklgie4omculZj6Ss3OzB2+YkmaVIg/TiEmoBee8MPBIpomdOhGwiZA2Hg2EFqjELYttyc9gZZy5A4oUc+uuTxe6rbW3IF6IqOcw5fDwysx0RXhpAT1H1RNcqepDQ15MaJlnm4BE1Pc9I3Dc3oRrEP8ZGXhkfaqKkHQ3NqdkcLGf1Wko3vaJnoXRl7eB92bib6J+8qXjlvs128fUaGQh4GoouandiYypA8Uge1jtFQ56R59embQbWJUFpw4fXnhWfHYlXBUMPujM+sz5V5yGaaL5E/yBbR2ixs81JBLwVKG6FGnCm4UXvPMm29NCUPQ3SY17V6m1uuxIfHWJ3f22CpRe2BIBFbktATHtQZYeRqAgKJDvU9KbGDDwGh+oRwG4kbgt7mVVajX11xE5LvSXIFPnCdHFBR4YXvoq5Q5pI6NQTlQqbtlqKyoJkM=